package forme;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import niti.ServerskaNit;

public class ServerskaForma extends javax.swing.JFrame {

    /**
     * Creates new form ServerskaForma
     */
    ServerskaNit sn;
    public ServerskaForma() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        btnServer = new javax.swing.JMenu();
        btnDiskonektuj = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        btnBaza = new javax.swing.JMenu();
        btnKonfigurisi = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnServer.setText("Server");

        btnDiskonektuj.setText("Konektuj se");
        btnDiskonektuj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDiskonektujActionPerformed(evt);
            }
        });
        btnServer.add(btnDiskonektuj);

        jMenuItem2.setText("Diskonektuj se");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        btnServer.add(jMenuItem2);

        jMenuBar1.add(btnServer);

        btnBaza.setText("Baza");

        btnKonfigurisi.setText("Konfigurisi bazu");
        btnKonfigurisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKonfigurisiActionPerformed(evt);
            }
        });
        btnBaza.add(btnKonfigurisi);

        jMenuBar1.add(btnBaza);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 274, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
          if (sn != null && sn.getServerSocket().isBound()) {
            try {
                sn.zaustaviServerskuNit();
                btnDiskonektuj.setEnabled(true);
                jMenuItem2.setEnabled(false);
            } catch (IOException ex) {
                
            }
        }
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void btnDiskonektujActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDiskonektujActionPerformed
         if (sn == null || !sn.isAlive()) {
            try {
                sn = new ServerskaNit();
                sn.start();
                btnDiskonektuj.setEnabled(false);
                jMenuItem2.setEnabled(true);
            } catch (IOException ex) {
                Logger.getLogger(ServerskaForma.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnDiskonektujActionPerformed

    private void btnKonfigurisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKonfigurisiActionPerformed
        JFrame jf = new KonfiguracijaForma(this);
        jf.setVisible(true);
        setEnabled(false);
    }//GEN-LAST:event_btnKonfigurisiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ServerskaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ServerskaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ServerskaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ServerskaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ServerskaForma().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu btnBaza;
    private javax.swing.JMenuItem btnDiskonektuj;
    private javax.swing.JMenuItem btnKonfigurisi;
    private javax.swing.JMenu btnServer;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    // End of variables declaration//GEN-END:variables
}
