package forme;

import domen.Automobil;
import domen.DomainObject;
import domen.Korisnik;
import domen.Kupac;
import domen.Narudzbina;
import domen.StavkaNarudzbine;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.io.IOException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.LinkedList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import kontroler.KontrolerKlijent;
import tabela.ModelTabeleStavkeNarudzbine;

public class UnesiNarudzbinuDijalog extends javax.swing.JDialog {

    /**
     * Creates new form UnesiNarudzbinuDijalog
     */
    String status = "insert";
    Narudzbina narudzbina;
    NarudzbinaForma parent;
    public UnesiNarudzbinuDijalog(Narudzbina n, NarudzbinaForma nf) {
        
        initComponents();
        
        setLocationRelativeTo(null);
        
        
        parent = nf;
        txtBezPDV.setEnabled(false);
        txtBezPDV.setEditable(false);
        txtSaPDV.setEnabled(false);
        txtSaPDV.setEditable(false);
        
        try {
            popuniKomboBox();
            popuniTabelu();
            if(n != null)
            {
                status = "update";
                narudzbina = n;
                popuniPolja(n);
                cmbKupac.setSelectedItem(n.getKupacID());
                System.out.println(n.getKupacID());
            }else{
                SimpleDateFormat sdf= new SimpleDateFormat("dd.MM.yyyy");
                lblDatum.setText(sdf.format(new Date())+"");
                txtBezPDV.setText(0+"");
                txtSaPDV.setText(0+"");
                
            }
        } catch (Exception ex) {
            Logger.getLogger(UnesiNarudzbinuDijalog.class.getName()).log(Level.SEVERE, null, ex);
        }
        addWindowListener(new WindowAdapter()
        {
            @Override
            public void windowClosing(WindowEvent e)
            {
                parent.setEnabled(true);
                dispose();
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        cmbAutomobil = new javax.swing.JComboBox();
        btnDodaj = new javax.swing.JButton();
        btnDodajNoviAuto = new javax.swing.JButton();
        btnObrisiStavku = new javax.swing.JButton();
        ckDodatak = new javax.swing.JCheckBox();
        ckPolovno = new javax.swing.JCheckBox();
        btnFilter = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnSacuvaj = new javax.swing.JButton();
        lblDatum = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtBezPDV = new javax.swing.JTextField();
        txtSaPDV = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        btnDodajNovogKupca = new javax.swing.JButton();
        cmbKorisnici = new javax.swing.JComboBox();
        cmbKupac = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel2.setText("Datum izdavanja:");

        jLabel3.setText("Automobil:");

        cmbAutomobil.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnDodaj.setText("Dodaj stavku");
        btnDodaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDodajActionPerformed(evt);
            }
        });

        btnDodajNoviAuto.setText("Dodaj novi automobil");
        btnDodajNoviAuto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDodajNoviAutoActionPerformed(evt);
            }
        });

        btnObrisiStavku.setText("Obrisi stavku");
        btnObrisiStavku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObrisiStavkuActionPerformed(evt);
            }
        });

        ckDodatak.setText("Dodaci");

        ckPolovno.setText("Polovno");

        btnFilter.setText("Filtriraj");
        btnFilter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFilterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(ckPolovno)
                        .addGap(79, 79, 79)
                        .addComponent(btnFilter))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(ckDodatak)
                            .addComponent(jLabel3))
                        .addGap(33, 33, 33)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnDodaj)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnObrisiStavku))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(cmbAutomobil, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(btnDodajNoviAuto)))))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(btnDodajNoviAuto, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(ckDodatak)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ckPolovno))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(btnFilter)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbAutomobil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDodaj)
                    .addComponent(btnObrisiStavku))
                .addGap(25, 25, 25))
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        btnSacuvaj.setText("Sacuvaj narudzbenicu");
        btnSacuvaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSacuvajActionPerformed(evt);
            }
        });

        lblDatum.setText("jLabel5");

        jLabel6.setText("Ukupan iznos bez PDV-a (EUR):");

        jLabel4.setText("Narudzbenicu izdao:");

        jLabel5.setText("Ukupan iznos sa PDV-om (EUR):");

        jLabel7.setText("Kupac:");

        btnDodajNovogKupca.setText("Dodaj novog kupca");
        btnDodajNovogKupca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDodajNovogKupcaActionPerformed(evt);
            }
        });

        cmbKorisnici.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cmbKupac.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(220, 220, 220)
                        .addComponent(btnSacuvaj))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 537, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel5))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblDatum)
                                    .addComponent(txtBezPDV)
                                    .addComponent(txtSaPDV)
                                    .addComponent(cmbKorisnici, 0, 179, Short.MAX_VALUE)
                                    .addComponent(cmbKupac, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnDodajNovogKupca, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(8, 8, 8)))))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lblDatum))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cmbKorisnici, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(btnDodajNovogKupca, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cmbKupac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtBezPDV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtSaPDV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67)
                .addComponent(btnSacuvaj)
                .addGap(57, 57, 57))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDodajNovogKupcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDodajNovogKupcaActionPerformed
        UnesiKupcaDijalog ukd = new UnesiKupcaDijalog(this,true);
        ukd.setVisible(true);
        //setEnabled(false);
    }//GEN-LAST:event_btnDodajNovogKupcaActionPerformed

    private void btnDodajNoviAutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDodajNoviAutoActionPerformed
        UnesiAutomobilDijalog uad=new UnesiAutomobilDijalog(this, true);
        uad.setVisible(true);
        //setEnabled(false);
    }//GEN-LAST:event_btnDodajNoviAutoActionPerformed

    private void btnFilterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFilterActionPerformed
        if(ckDodatak.isSelected() && ckPolovno.isSelected()){
            try {
                filter();
            } catch (Exception ex) {
                Logger.getLogger(UnesiNarudzbinuDijalog.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else if(ckDodatak.isSelected() && !ckPolovno.isSelected()){
            try {
                filter2();
            } catch (Exception ex) {
                Logger.getLogger(UnesiNarudzbinuDijalog.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else if(!ckDodatak.isSelected() && ckPolovno.isSelected()){
            try {
                filter3();
            } catch (Exception ex) {
                Logger.getLogger(UnesiNarudzbinuDijalog.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else{
            try {
                popuniKomboBox();
            } catch (Exception ex) {
                Logger.getLogger(UnesiNarudzbinuDijalog.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnFilterActionPerformed

    private void btnObrisiStavkuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObrisiStavkuActionPerformed
        int row = jTable1.getSelectedRow();
        if(row != -1){
        ModelTabeleStavkeNarudzbine mtsn = (ModelTabeleStavkeNarudzbine) jTable1.getModel();
        StavkaNarudzbine st=mtsn.vratiStavku(row);
        mtsn.obrisi(row);
        srediCene2(st);
        
        }
    }//GEN-LAST:event_btnObrisiStavkuActionPerformed

    private void btnDodajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDodajActionPerformed
        Automobil a = (Automobil) cmbAutomobil.getSelectedItem();
        ModelTabeleStavkeNarudzbine mtsn = (ModelTabeleStavkeNarudzbine) jTable1.getModel();
        StavkaNarudzbine st=new StavkaNarudzbine(null, -1, a.getCenaBezPDV(), a.getCenaSaPDV(), a);
        mtsn.dodaj(st);
        srediCene(st);
        
    }//GEN-LAST:event_btnDodajActionPerformed

    private void btnSacuvajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSacuvajActionPerformed
        SimpleDateFormat sdf= new SimpleDateFormat("dd.MM.yyyy");    
        try {
            
            Date datumIzdavanja=sdf.parse(sdf.format(new Date()));
            Korisnik korisnik=(Korisnik) cmbKorisnici.getSelectedItem();
            Kupac kupac=(Kupac) cmbKupac.getSelectedItem();
            ModelTabeleStavkeNarudzbine mtsn=(ModelTabeleStavkeNarudzbine) jTable1.getModel();
            LinkedList<StavkaNarudzbine>lista=mtsn.vratiListu();

            double ukupanIznosBezPDV=0;
            double ukupanIznosSaPDV=0;
            
            for (StavkaNarudzbine stavkaNarudzbine : lista) {
                ukupanIznosBezPDV+=stavkaNarudzbine.getIznosStavkiNarudzbineBezPDV();
                ukupanIznosSaPDV+=stavkaNarudzbine.getIznosStavkiNarudzbineSaPDV();
            }
            
            Narudzbina n= new Narudzbina(-1, datumIzdavanja, ukupanIznosBezPDV, ukupanIznosSaPDV, kupac, korisnik, lista);

        try {
            if (status.equals("insert")){
                n = KontrolerKlijent.getInstance().dodajNarudzbinu(n);
                if(n.getNarudzbinaID()!= -1){
                    JOptionPane.showMessageDialog(this, "Uspesno ubacena nova narudzbina");
                    parent.setEnabled(true);
                    parent.osvezi();
                    dispose();
                }
                else JOptionPane.showMessageDialog(this, "Narudzbina nije uneta");
            }
            else{
              n.setNarudzbinaID(narudzbina.getNarudzbinaID());
              n = KontrolerKlijent.getInstance().izmeniNarudzbinu(n);
              
                JOptionPane.showMessageDialog(this, "Uspesno izmenjena narudzbina!");
                parent.setEnabled(true);
                parent.osvezi();
                dispose();
              
              
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Greska pri izmeni narudzbenice"+ex.getMessage());
        }
        } catch (ParseException ex) {
            Logger.getLogger(UnesiNarudzbinuDijalog.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnSacuvajActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UnesiNarudzbinuDijalog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UnesiNarudzbinuDijalog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UnesiNarudzbinuDijalog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UnesiNarudzbinuDijalog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDodaj;
    private javax.swing.JButton btnDodajNoviAuto;
    private javax.swing.JButton btnDodajNovogKupca;
    private javax.swing.JButton btnFilter;
    private javax.swing.JButton btnObrisiStavku;
    private javax.swing.JButton btnSacuvaj;
    private javax.swing.JCheckBox ckDodatak;
    private javax.swing.JCheckBox ckPolovno;
    private javax.swing.JComboBox cmbAutomobil;
    private javax.swing.JComboBox cmbKorisnici;
    private javax.swing.JComboBox cmbKupac;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblDatum;
    private javax.swing.JTextField txtBezPDV;
    private javax.swing.JTextField txtSaPDV;
    // End of variables declaration//GEN-END:variables

    private void popuniTabelu() {
        ModelTabeleStavkeNarudzbine mtsn= new ModelTabeleStavkeNarudzbine(new LinkedList<StavkaNarudzbine>());
        jTable1.setModel(mtsn);
    }
    
    void osvezi() throws IOException, Exception{
        popuniKomboBox();
    }

    private void popuniKomboBox() throws IOException, Exception {
        cmbAutomobil.removeAllItems();
        cmbKupac.removeAllItems();
        cmbKorisnici.removeAllItems();
        LinkedList<DomainObject> automobili= KontrolerKlijent.getInstance().vratiAutomobile();
        LinkedList<DomainObject> kupci= KontrolerKlijent.getInstance().vratiKupce();
        LinkedList<DomainObject> korisnici= KontrolerKlijent.getInstance().vratiKorisnike();
        for (DomainObject auto : automobili) {
            cmbAutomobil.addItem(auto);
        }
        for (DomainObject kupac : kupci) {
            cmbKupac.addItem(kupac);
        }
        for (DomainObject korisnik : korisnici) {
            cmbKorisnici.addItem(korisnik);
        }
        
    }

    private void popuniPolja(Narudzbina n) {
        SimpleDateFormat sdf= new SimpleDateFormat("dd.MM.yyyy");
        lblDatum.setText(sdf.format(n.getDatumIzdavanja())+"");
        System.out.println(n.getKupacID());
        cmbKupac.setSelectedItem(n.getKupacID());
        cmbKorisnici.setSelectedItem(n.getKorisnikID());
        
        txtBezPDV.setText(n.getUkupanIznosBezPDV()+"");
        txtSaPDV.setText(n.getUkupanIznosSaPDV()+"");
        
        LinkedList<StavkaNarudzbine> stavke=n.getStavke();
        
        ModelTabeleStavkeNarudzbine mtsn = (ModelTabeleStavkeNarudzbine) jTable1.getModel();
        for (StavkaNarudzbine stavkaNarudzbine : stavke) {
            mtsn.dodaj(stavkaNarudzbine);
        }
    }

    private void filter() throws IOException, Exception {
        LinkedList<DomainObject> automobili= KontrolerKlijent.getInstance().vratiAutomobile();
        cmbAutomobil.removeAllItems();
        for (DomainObject auto : automobili) {
            if(((Automobil)auto).isDodaci() && ((Automobil)auto).isPolovno()){
                cmbAutomobil.addItem(auto);
            }
        }
    }

    private void filter2() throws IOException, Exception {
        LinkedList<DomainObject> automobili= KontrolerKlijent.getInstance().vratiAutomobile();
        cmbAutomobil.removeAllItems();
        for (DomainObject auto : automobili) {
            if(((Automobil)auto).isDodaci() && ((Automobil)auto).isPolovno()==false){
                cmbAutomobil.addItem(auto);
            }
        }
    }

    private void filter3() throws IOException, Exception {
        LinkedList<DomainObject> automobili= KontrolerKlijent.getInstance().vratiAutomobile();
        cmbAutomobil.removeAllItems();
        for (DomainObject auto : automobili) {
            if(((Automobil)auto).isDodaci()==false && ((Automobil)auto).isPolovno()){
                cmbAutomobil.addItem(auto);
            }
        }
    }

    private void srediCene(StavkaNarudzbine st) {
        double iznosBez=Double.parseDouble(txtBezPDV.getText());
        double iznosSa=Double.parseDouble(txtSaPDV.getText());
        
        iznosBez+=st.getIznosStavkiNarudzbineBezPDV();
        iznosSa+=st.getIznosStavkiNarudzbineSaPDV();
        
        txtBezPDV.setText(iznosBez+"");
        txtSaPDV.setText(iznosSa+"");
    }

    private void srediCene2(StavkaNarudzbine st) {
        double iznosBez=Double.parseDouble(txtBezPDV.getText());
        double iznosSa=Double.parseDouble(txtSaPDV.getText());
        
        iznosBez-=st.getIznosStavkiNarudzbineBezPDV();
        iznosSa-=st.getIznosStavkiNarudzbineSaPDV();
        
        txtBezPDV.setText(iznosBez+"");
        txtSaPDV.setText(iznosSa+"");
    }

   
}
