package forme;

import domen.Automobil;
import domen.TipAutomobila;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.GregorianCalendar;
import java.util.Properties;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import kontroler.KontrolerKlijent;

public class UnesiAutomobilDijalog extends javax.swing.JDialog {

    /**
     * Creates new form UnesiAutomobilDijalog
     */
    UnesiNarudzbinuDijalog parent;
    public UnesiAutomobilDijalog(UnesiNarudzbinuDijalog parent, boolean modal) {
        
        initComponents();
        setLocationRelativeTo(null);
        this.parent=parent;
        
        popuniKomboBox();
        
                addWindowListener(new WindowAdapter()
        {
            @Override
            public void windowClosing(WindowEvent e)
            {
                parent.setEnabled(true);
                dispose();
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnUnesi = new javax.swing.JButton();
        txtCena = new javax.swing.JTextField();
        txtMarka = new javax.swing.JTextField();
        cmbGodiste = new javax.swing.JComboBox();
        cmbTip = new javax.swing.JComboBox();
        ckDodatak = new javax.swing.JCheckBox();
        ckPolovno = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Marka:");

        jLabel2.setText("Godiste:");

        jLabel3.setText("Tip:");

        jLabel6.setText("Cena bez PDV-a (EUR):");

        btnUnesi.setText("UNESI AUTOMOBIL");
        btnUnesi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUnesiActionPerformed(evt);
            }
        });

        cmbGodiste.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cmbTip.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        ckDodatak.setText("Dodaci");

        ckPolovno.setText("Polovno");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ckDodatak)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                                .addComponent(ckPolovno))
                            .addComponent(txtCena, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtMarka, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbGodiste, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmbTip, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addComponent(btnUnesi)))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(txtMarka, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cmbGodiste, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(cmbTip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ckPolovno)
                    .addComponent(ckDodatak))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtCena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addComponent(btnUnesi)
                .addGap(61, 61, 61))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnUnesiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUnesiActionPerformed
        String marka=txtMarka.getText();
        int godiste=(int) cmbGodiste.getSelectedItem();
        TipAutomobila tip=(TipAutomobila) cmbTip.getSelectedItem();
        boolean dodaci=ckDodatak.isSelected();
        boolean polovan=ckPolovno.isSelected();
        if(txtCena.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Polje cene ne sme biti prazno");
        }else{
            double cenaBezPDV=Double.parseDouble(txtCena.getText());
            try {
                 FileInputStream in = new FileInputStream("pdv.properties");
                 Properties props = new Properties();
                 props.load(in);
                 String PDV = props.getProperty("PDV");
                 double pdvIznos=Double.parseDouble(PDV);
                 double cenaSaPDV=(((100*pdvIznos)/(100+pdvIznos))*100)+cenaBezPDV;
                 cenaSaPDV=Math.round(cenaSaPDV);
                 Automobil a= new Automobil(-1, marka, godiste, tip, dodaci, polovan, cenaBezPDV, cenaSaPDV);
            
                 a=KontrolerKlijent.getInstance().unesiAutomobil(a);
                 if(a.getAutomobilID()!=-1){
                    JOptionPane.showMessageDialog(this, "Uspesno unet automobil");
                    parent.osvezi();
                    this.dispose();
                }else{
                JOptionPane.showMessageDialog(this, "Nije unet automobil");
                }
            
            
            } catch (FileNotFoundException ex) {
            Logger.getLogger(UnesiAutomobilDijalog.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
            Logger.getLogger(UnesiAutomobilDijalog.class.getName()).log(Level.SEVERE, null, ex);
            } catch (Exception ex) {
            Logger.getLogger(UnesiAutomobilDijalog.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Auto postoji u bazi");
            }
        }
   
    }//GEN-LAST:event_btnUnesiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UnesiAutomobilDijalog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UnesiAutomobilDijalog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UnesiAutomobilDijalog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UnesiAutomobilDijalog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>


    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnUnesi;
    private javax.swing.JCheckBox ckDodatak;
    private javax.swing.JCheckBox ckPolovno;
    private javax.swing.JComboBox cmbGodiste;
    private javax.swing.JComboBox cmbTip;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField txtCena;
    private javax.swing.JTextField txtMarka;
    // End of variables declaration//GEN-END:variables

    private void popuniKomboBox() {
        cmbGodiste.removeAllItems();
        cmbTip.removeAllItems();
        
        for (Enum tip : TipAutomobila.values()) {
            cmbTip.addItem(tip);
        }
        
        for (int i = 2000; i <= new GregorianCalendar().get(GregorianCalendar.YEAR); i++) {
            cmbGodiste.addItem(i);
        }
    }
}
